feat(fix): move component data files into page bundles

diff --git a/bin/release/prerelease b/bin/release/prerelease
--- a/bin/release/prerelease
+++ b/bin/release/prerelease
@@ -1,30 +1,33 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-  git
-  hugo
-  typos
+	git
+	hugo
+	typos
+	curl
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
-    exit 1
-  fi
+	if ! command -v "${TOOL}" >/dev/null; then
+		echo "${TOOL} is required... "
+		exit 1
+	fi
 done
 
 SCRIPTPATH="$(
-  cd "$(dirname "$0")" >/dev/null 2>&1 || exit
-  pwd -P
+	cd "$(dirname "$0")" >/dev/null 2>&1 || exit
+	pwd -P
 )"
 CURPATH="$(pwd -P)"
 
 typos -- ./content
 
+"${CURPATH}"/bin/build/component-tags
+
 if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -dropreplace "${__[0]}"
-  done <"$SCRIPTPATH"/replacements
+	while read -ra __; do
+		go mod edit -dropreplace "${__[0]}"
+	done <"$SCRIPTPATH"/replacements
 fi
 
 #"${CURPATH}"/bin/build/prepare-docs
@@ -35,11 +38,11 @@ hugo mod tidy
 git add "${CURPATH}"/go.mod
 FILE="${CURPATH}"/go.sum
 if test -f "$FILE"; then
-  git add go.sum
+	git add go.sum
 fi
 
 if test -f "$SCRIPTPATH"/replacements; then
-  while read -ra __; do
-    go mod edit -replace "${__[0]}"="${__[1]}"
-  done <"$SCRIPTPATH"/replacements
+	while read -ra __; do
+		go mod edit -replace "${__[0]}"="${__[1]}"
+	done <"$SCRIPTPATH"/replacements
 fi
