fix: smaller fixes to dependencies script

diff --git a/bin/repo/maintenance/dependencies b/bin/repo/maintenance/dependencies
--- a/bin/repo/maintenance/dependencies
+++ b/bin/repo/maintenance/dependencies
@@ -1,7 +1,7 @@
 #!/bin/bash
-# v20231105001
+# v20231106001
 
-# set -euo pipefail # http://redsymbol.net/articles/unofficial-bash-strict-mode
+set -euo pipefail # http://redsymbol.net/articles/unofficial-bash-strict-mode
 IFS=$'\n\t'
 
 # @todo quick check (just return status code)
@@ -10,12 +10,15 @@ REQUIRED_TOOLS=(
   git
 )
 
-# check if all requirements are met
-for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
+check_tool() {
+  if ! command -v "$1" >/dev/null; then
+    echo "$1 is required..."
     exit 1
   fi
+}
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  check_tool "$TOOL"
 done
 
 FILE=.env
@@ -36,13 +39,16 @@ IFS=$'\n\t'
 CHANGES=false
 for DEPENDENCY in "${DEPENDENCIES_PARSED[@]}"; do
   cd ../"${DEPENDENCY}" >/dev/null || return
-  if [ "$(git status --porcelain | wc -l)" -eq "0" ]; then
-    continue
-  else
-    CHANGES=true
-    echo -e "\e[1;36m${DEPENDENCY}\e[m"
-    if [ -d .git ]; then
+  if [ -d .git ]; then
+    if [ "$(git status --porcelain | wc -l)" -ne "0" ]; then
+      CHANGES=true
+      echo -e "\e[1;36m${DEPENDENCY}\e[m"
       git status -s
+    fi
+    if [ "$(git stash list | wc -l)" -ne "0" ]; then
+
+      printf "\e[1;36m%s\e[m\n${DEPENDENCY}\e[m"
+      git stash list
     fi
   fi
 done
@@ -53,9 +59,9 @@ if [ ${CHANGES} = true ]; then
   for DEPENDENCY in "${DEPENDENCIES_PARSED[@]}"; do
     cd ../"${DEPENDENCY}" >/dev/null || echo ${DEPENDENCY} not found
     if [ "$(git status --porcelain | wc -l)" -eq "0" ]; then
-      echo "🟢 ${DEPENDENCY}"
+      printf "\e[1;36m%s\e[m\n" "🟢 ${DEPENDENCY}"
     else
-      echo "🟠 ${DEPENDENCY}"
+      printf "\e[1;36m%s\e[m\n" "🟠 ${DEPENDENCY}"
     fi
   done
 fi
@@ -68,8 +74,5 @@ else
   echo
   exit 1
 fi
-
-set -euo pipefail # http://redsymbol.net/articles/unofficial-bash-strict-mode
-IFS=$'\n\t'
 
 # nc -w 10 -z 192.168.1.201 1313
