build: fix build scripts

diff --git a/bin/netlify/build b/bin/netlify/build
--- a/bin/netlify/build
+++ b/bin/netlify/build
@@ -1,21 +1,22 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-	hugo
-	npm
+  hugo
+  npm
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-	if ! command -v "${TOOL}" >/dev/null; then
-		echo "${TOOL} is required... "
-		exit 1
-	fi
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
 done
 
 hugo mod get -u ./...
 hugo mod tidy
+
 rm -rf public/
-./bin/build/hugo
+hugo
 npm run pagefind
 
 # cleaning up
