chore(github): update netlify update script

diff --git a/bin/netlify/update-hugo-version b/bin/netlify/update-hugo-version
--- a/bin/netlify/update-hugo-version
+++ b/bin/netlify/update-hugo-version
@@ -1,20 +1,20 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-  cat
+	cat
 )
 
 for TOOL in "${REQUIRED_TOOLS[@]}"; do
-  if ! command -v "${TOOL}" >/dev/null; then
-    echo "${TOOL} is required... "
-    exit 1
-  fi
+	if ! command -v "${TOOL}" >/dev/null; then
+		echo "${TOOL} is required... "
+		exit 1
+	fi
 done
 
 get_latest_release() {
-  curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" |
-    grep '"tag_name":' |
-    sed -E 's/.*"v([^"]+)".*/\1/'
+	curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" |
+		grep '"tag_name":' |
+		sed -E 's/.*"v([^"]+)".*/\1/'
 }
 
 cat <<EOF
@@ -25,7 +25,7 @@ publish = "./public"
 command = "./bin/netlify/build"
 
 [context.production.environment]
-HUGO_VERSION = "$(get_latest_release)"
+HUGO_VERSION = "0.104.3"
 HUGO_ENV = "production"
 GO_VERSION = "1.17"
 NODE_ENV = "development"
@@ -34,35 +34,8 @@ NODE_ENV = "development"
 package = "/bin/netlify/plugins/hugo-helper"
 
 [plugins.inputs]
-debug = true
+debug = false
 
-[[redirects]]
-from = "https://main--kollitsch.netlify.app/"
-to = "/"
-status = 301
-
-[[redirects]]
-from = "/repos/*"
-to = "/"
-status = 301
-
-[[redirects]]
-from = "/2005/*"
-to = "/"
-status = 301
-
-[[redirects]]
-from = "/2006/*"
-to = "/"
-status = 301
-
-[[redirects]]
-from = "/2007/*"
-to = "/"
-status = 301
-
-[[redirects]]
-from = "/2008/*"
-to = "/"
-status = 301
+# [[plugins]]
+# package = "netlify-plugin-image-optim"
 EOF
